export const ROUTES = {
  home: "/",
  tools: "/tools",
  wishbook: "/wishbook",
  futureMessages: "/future-messages",
  seating: "/seating",
  rsvp: "/rsvp",
  gifts: "/gifts",
  venue: "/venue",
  schedule: "/schedule",
  notifications: "/notifications",
  profile: "/profile",
  invitation: "/invitation",
  quiz: "/quiz",
  newPost: "/post/new",
  post: (postId: string) => `/post/${postId}`,
  comments: (postId: string) => `/post/${postId}/comments`,
  story: (storyId: string) => `/story/${storyId}`,
} as const;
